name: build
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_ADMIN_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
    - name: Checkout config repo
      uses: actions/checkout@v2
      with:
        token: "${{ secrets.GH_ADMIN_TOKEN }}"
        repository: "${{ github.repository }}-config"
        path: '.config-repo'
    - name: Kustomize Edit image
      uses: williamhogman/kustomize-set-image-hook@v1.5
      with:
        workingDirectory: .config-repo/
        kustomizePath: prod
        name: app-image
        newName: ghcr.io/${{ github.repository }}
        newTag: ${{ github.sha }}